plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def version_code = 16
def version_major = 1
def version_minor = 2
def version_patch = 6
def version_name = "${version_major}.${version_minor}.${version_patch}"

Properties localProperties = new Properties()
localProperties.load(project.file('local.properties').newDataInputStream())
def GOOGLE_SERVICES_ENABLED = localProperties['com.google.services.enabled'] == 'true'

android {
    namespace 'com.chat.app'
    compileSdk 34

    signingConfigs {
        release {
            def configDir = getReleaseConfigDir()
            def releaseConfigs = loadProperties("$configDir/signing.properties")
            storeFile file("$configDir/${releaseConfigs['storeFile']}")
            storePassword releaseConfigs['storePassword']
            keyAlias releaseConfigs['keyAlias']
            keyPassword releaseConfigs['keyPassword']
        }
    }

    defaultConfig {
        applicationId "com.chat.bot"
        minSdk 23
        targetSdk 34
        versionCode version_code
        versionName version_name

        buildConfigField "boolean", "GOOGLE_SERVICES_ENABLED", GOOGLE_SERVICES_ENABLED.toString()
//        buildConfigField "String", "OPEN_AI_API_KEY", "\"${localProperties.getProperty('openai.apikey') ?: ""}\""
        buildConfigField "String", "DEEPSEEK_API_KEY", "\"${localProperties.getProperty('deepseek.apikey') ?: ""}\""
        buildConfigField "String", "ADMOB_INTERSTIAIL_AD_UNIT_ID", "\"${localProperties.getProperty('admob.interstitial_ad_unit_id') ?: ""}\""

        resValue "string", "admob_app_id", "\"${localProperties.getProperty('admob.app_id') ?: ""}\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            resValue "string", "app_name", "Chat GPT"
        }
        debug {
            minifyEnabled false
            shrinkResources false
            applicationIdSuffix ".debug"
            resValue "string", "app_name", "Chat GPT Debug"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        buildConfig true
    }
}

configurations {
    cleanedAnnotations
    implementation.exclude group: 'org.jetbrains' , module:'annotations'
}

dependencies {
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation("com.squareup.okhttp3:okhttp:4.10.0")

    implementation project(path: ':chat-core')
    implementation project(path: ':chat-ui')

    implementation project(path: ':utils')
    implementation project(path: ':firebase')

    implementation 'com.google.android.gms:play-services-ads:22.1.0'

    implementation platform('com.google.firebase:firebase-bom:31.2.3')
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
}

if (GOOGLE_SERVICES_ENABLED) {
    apply plugin: 'com.google.gms.google-services'
    apply plugin: 'com.google.firebase.crashlytics'
}